# Determine the absolute path to the "nawk" program (or something
# compatible with POSIX.2 "awk").
# Print it as a Makefile definition to stdout, and set equivalent
# environment variables.
#

echo "searching for POSIX.2 \"awk\" or compatible" 1>&2


# assume worst, until proven otherwise
#
prog="/a_POSIX2_awk_or_compatible"

# build list of directories to search
#
list="`echo ${PATH} | sed -e 's/:/ /g'`"
list="$list /bin /usr/bin /usr/sbin /sbin /usr/xpg4/bin"


# create a "nawk" script that old "awk" will not be able to handle...
# eg: a script that uses "gsub()"...
#
cat > /tmp/$$.tmp << 'EOT'
{ gsub("[0-9]", ""); print $1 }
EOT


# search for likely program:
#
for d in $list ; do
	for p in nawk gawk mawk ; do
		if [ -f ${d}/$p ] && [ -x $d/$p ] ; then
			NAWK="$d/$p"
			break 2
		fi
	done

	# Hmmm. Maybe the "awk" program is POSIX.2 compatible on this system?
	#
	if [ -f $d/awk ] && [ -x $d/awk ] ; then
		# test it!
		if [ "`echo '0n1a2w3k4' | $d/awk -f /tmp/$$.tmp 2>/dev/null`" = "nawk" ] ; then
			NAWK=$d/awk
			break
		fi
	fi
done

# and output...
#
if [ "$NAWK" = "" ] ; then
	status=1
	NAWK="/path/programname"
	echo '\007' 1>&2
	cat << EOT 1>&2
	********************  W A R N I N G  ************************
	******							*****
	******  Cannot locate POSIX.2-compatible "awk" utility  *****
	******							*****
	*************************************************************

	Some UNIX systems have a suitable "awk" utility, but do not install
	it by default. Check your operating-system install media to see if
	you can install nawk, mawk, gawk, or a POSIX.2-conformant awk.

	If your system does not provide such a utility even as an option,
	you should obtain one of the freely-available versions, such as
	mawk or GNU gawk (these are available from numerous download sites).

	You should then rerun this script. If you have already done this
	and are still getting this warning, you will need to manually
	adjust the following setting in the makefile generated by this script:

		NAWK=/path/programname

EOT
	echo "Press RETURN to continue \c" 1>&2
	read dummy
	echo "" 1>&2
fi

cat << EOT

# Full pathname of a program compatible with POSIX.2 "awk":
# (such as SVR4 nawk, GNU gawk, mawk or XPG4 awk;
# old awks lacking "gsub()" et al are NOT suitable).
#
NAWK=$NAWK

EOT

export NAWK
